sudo: false
language: python
dist: xenial
cache: docs
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=check
install:
  - pip install -r requirements.txt
  - pip install tox-travis coveralls pdoc3
script: tox
after_success: 
  - coveralls
  - pdoc pyfavicon --html -o ./docs

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html/pyfavicon/
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
